### ISSUE TITLE
Plugin causes IDEA to hang on project load

### ISSUE THREAD

**Issue by Mart-Bogdan** [dmarks2/maven-archetypes-catalog-plugin#4]
here is IDEA's log file https://www.dropbox.com/s/rg1m89ef61d8det/idea.log?dl=0
I'm unable to reproduce anymore, as I've removed all plugins and cleared Idea settings, to run projects, but JB support told me, that problem is in your plugin

**Comment by dmarks2** [comment]
can you tell me what you exactly did when the plugin crashed? Did it crash while starting IDEA, while opening the configuration, while creating a new project based on a maven archetype or something else? On which type of project did the plugin crash? Was it a maven project? If yes, could you send me the pom.xml?

**Comment by Mart-Bogdan** [comment]
Hello, it first happened, when I've opened following project https://intellij-support.jetbrains.com/attachments/token/i2bpn7jEo3xoVPsYqfgDs2NIP/?name=jmh-benchmarks.zip
After that I wasn't able to open any project. no gradle, no IPR based.

Afer that I've cleared my profiled and disabled all plugins, so I can't reproduce it now, but Guys from jetbrain support pointed me that your plugin was the cause :(

**Comment by dmarks2** [comment]
Hello,

I was really unable to reproduce the problem. Are you sure it was caused by my plugin? I could not find anything related to my plugin in the log file you sent me. 

I found some references to the Plugin "Maven Archetypes" (https://plugins.jetbrains.com/plugin/1789) in the Log file. That plugin is not developed by me. My plugin is called "Maven Archetypes Catalog" (https://plugins.jetbrains.com/plugin/7965).
